# Generated by Django 2.0.7 on 2019-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfomodel',
            old_name='portfolio_url',
            new_name='portfolio_site',
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='basic_app/profile_pics'),
        ),
    ]
